AWSTemplateFormatVersion: 2010-09-09
Description: "ver 0.0.1"

Metadata: ""

Parameters: 
  TagName:
    Description: "Name of the tags used for the Application"
    Type: String
  BucketName:
    Description: "Bucket Name"
    Type: String
  LambdaName:
    Description: "Name of the Function"
    Type: String
  TableName: 
    Description: "Name of the DDB Table"
    Type: String
  PartitionKeyName:
    Description: "Partition Key Name"
    Type: String
  RoleName:
    Description: "Role Name"
    Type: String
  ApiName:
    Description: "Name of teh REST API"
    Type: String

Mappings: ""

Conditions: ""

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName:
        Ref: BucketName
      Tags:
        - Key: Webapp
          Value:
            Ref: TagName
  
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Ref: LambdaName
      Handler: index.lambda_handler
      MemorySize: 128
      Role: role-arn
      Runtime: nodejs18.x
      Environment:
        Variables:
          key1: value1
      Code:
        S3Bucket: 
        S3Key: 
        S3ObjectVersion: 
        ZipFile: 
      Tags:
        - Key: Webapp
          Value:
            Ref: TagName

  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: DDBTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 
          Ref: PartitionKeyName
          AttributeType: S
      KeySchema:
        - AttributeName:
          Ref: PartitionKeyName
          KeyType: HASH
      Tags: 
        - Key: Webapp
          Value: 
            Ref: TagName

  RestAPI:
  Type: AWS::ApiGateway::RestApi
  Properties: 
    Name: 
      Ref: ApiName
      Tags: 
        - Key: Webapp
          Value: 
            Ref: TagName

Outputs:
  LambdaARN:
    Value:
      GetAtt: lambdaFunction.Arn
  S3BucketArn:
    Value:
      GetAtt: s3Bucket.Arn
  DynamoDBTableArn:
    Value:
      GetAtt: dynamodbTable.Arn
  RestAPIArn:
    Value:
      GetAtt: RestAPI.Arn
      