AWSTemplateFormatVersion: 2010-09-09
Description: "ver 0.0.2"

Metadata: ""

Parameters: 
  TagName:
    Description: "Name of the tags used for the Application"
    Type: String
  BucketName:
    Description: "Bucket Name"
    Type: String
  LambdaName:
    Description: "Name of the Function"
    Type: String
  RoleName:
    Description: "Role Name"
    Type: String
  ApiName:
    Description: "Name of teh REST API"
    Type: String

Mappings: ""

Conditions: ""

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
    Tags:
      - Key: Webapp
        Value: !Ref TagName
  
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Handler: index.lambda_handler
      MemorySize: 128
      Role: role-arn
      Runtime: nodejs18.x
      Environment:
        Variables:
          key1: value1
      Code:
        S3Bucket: 
        S3Key: 
        S3ObjectVersion: 
        ZipFile: 
      Tags:
        - Key: Webapp
          Value: !Ref TagName

  comboTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Combos
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: ServerID
          AttributeType: N
        - AttributeName: ComboID
          AttributeType: N
        - AttributeName: Character
          AttributeType: S
        - AttributeName: Input
          AttributeType: S
        - AttributeName: Video
          AttributeType: S
        - AttributeName: Credit
          AttributeType: S
        - AttributeName: Damage
          AttributeType: N
        - AttributeName: Tags
          AttributeType: S
        - AttributeName: Starter
          AttributeType: S
        - AttributeName: Notes
          AttributeType: S
        - AttributeName: Game Version
          AttributeType: S
        - AttributeName: Created At
          AttributeType: S
        - AttributeName: Updated At
          AttributeType: S
        - AttributeName: Added By
          AttributeType: S
      KeySchema:
        - AttributeName: ServerID
          KeyType: HASH
        - AttributeName: ComboID
          KeyType: RANGE
      ProvisionedCapacitySettings:
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      Tags: 
        - Key: Webapp
          Value: !Ref TagName

  RestAPI:
  Type: AWS::ApiGateway::RestApi
  Properties: 
    Name: !Ref ApiName
    Tags: 
      - Key: Webapp
        Value: !Ref TagName

Outputs:
  LambdaARN:
    Value: !GetAtt lambdaFunction.Arn
  S3BucketArn:
    Value: !GetAtt s3Bucket.Arn
  DynamoDBTableArn:
    Value: !GetAtt dynamodbTable.Arn
  RestAPIArn:
    Value: !GetAtt RestAPI.Arn
      