AWSTemplateFormatVersion: 2010-09-09
Description: "ver 0.0.4"

Metadata: ""

Parameters: ""

Mappings: ""

Conditions: ""

Resources: 
  websiteBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: website-41722369
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Webapp
          Value: GGSTCombo01
  
  templateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      BucketName: cf-templates-264759380
      Tags:
        - Key: Webapp
          Value: GGSTCombo01

  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ggstLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
      Policies:
        - PolicyName: ggst-log-group-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:us-east-1:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/lambda/codeExample:*
      Tags:
        - Key: Webapp
          Value: GGSTCombo01
  
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: codeExample
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt lambdaRole.Arn
      Runtime: nodejs18.x
      Environment:
        Variables:
          example: value
      Code:
        ZipFile: |
          const http = require('http');
          
          const hostname = '127.0.0.1';
          const port = 3000;
          
          const server = http.createServer((req, res) => {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/plain');
            res.end('Hello World');
          });
          
          server.listen(port, hostname, () => {
            console.log(`Server running at http://${hostname}:${port}/`);
          }); 
      Tags:
        - Key: Webapp
          Value: GGSTCombo01

  comboTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Combos
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: ServerID
          AttributeType: N
        - AttributeName: ComboID
          AttributeType: N
        - AttributeName: Character
          AttributeType: S
        - AttributeName: Input
          AttributeType: S
        - AttributeName: Video
          AttributeType: S
        - AttributeName: Credit
          AttributeType: S
        - AttributeName: Damage
          AttributeType: N
        - AttributeName: Tags
          AttributeType: S
        - AttributeName: Starter
          AttributeType: S
        - AttributeName: Notes
          AttributeType: S
        - AttributeName: Game Version
          AttributeType: S
        - AttributeName: Created At
          AttributeType: S
        - AttributeName: Updated At
          AttributeType: S
        - AttributeName: Added By
          AttributeType: S
      KeySchema:
        - AttributeName: ServerID
          KeyType: HASH
        - AttributeName: ComboID
          KeyType: RANGE
      ProvisionedCapacitySettings:
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      Tags: 
        - Key: Webapp
          Value: GGSTCombo01

  restAPI:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: comboAPI
      ApiKeySourceType: "HEADER"
      EndpointConfiguration: 
          Types: 
            - "REGIONAL"
      Tags: 
        - Key: Webapp
          Value: GGSTCombo01

  apiResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
          RestApiId: !Ref restAPI
          PathPart: "combo"
          ParentId: !GetAtt restAPI.RootResourceId

  RootGETMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
          RestApiId: !Ref restAPI
          ResourceId: !GetAtt restAPI.RootResourceId
          HttpMethod: "GET"
          AuthorizationType: "NONE"
          ApiKeyRequired: false
          RequestParameters: {}
          MethodResponses: 
            - 
              ResponseModels: 
                  "application/json": !Ref ApiGatewayModel
              StatusCode: "200"
          Integration: 
              CacheNamespace: !GetAtt restAPI.RootResourceId
              IntegrationResponses: 
                - 
                  ResponseTemplates: {}
                  StatusCode: "200"
              PassthroughBehavior: "WHEN_NO_MATCH"
              RequestTemplates: 
                  "application/json": "{\"statusCode\": 200}"
              TimeoutInMillis: 29000
              Type: "MOCK"

  RootPOSTMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
          RestApiId: !Ref restAPI
          ResourceId: !GetAtt restAPI.RootResourceId
          HttpMethod: "POST"
          AuthorizationType: "NONE"
          ApiKeyRequired: false
          RequestParameters: {}
          MethodResponses: 
            - 
              ResponseModels: 
                  "application/json": !Ref ApiGatewayModel
              StatusCode: "200"
          Integration: 
              CacheNamespace: !GetAtt restAPI.RootResourceId
              IntegrationResponses: 
                - 
                  ResponseTemplates: {}
                  StatusCode: "200"
              PassthroughBehavior: "WHEN_NO_MATCH"
              RequestTemplates: 
                  "application/json": "{\"statusCode\": 200}"
              TimeoutInMillis: 29000
              Type: "MOCK"

  comboANYMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
          RestApiId: !Ref restAPI
          ResourceId: !Ref apiResource
          HttpMethod: "ANY"
          AuthorizationType: "NONE"
          ApiKeyRequired: false
          RequestParameters: {}
          MethodResponses: 
            - 
              ResponseModels: 
                  "application/json": !Ref ApiGatewayModel
              StatusCode: "200"
          Integration: 
              CacheNamespace: !Ref apiResource
              IntegrationResponses: 
                - 
                  ResponseTemplates: {}
                  StatusCode: "200"
              PassthroughBehavior: "WHEN_NO_MATCH"
              RequestTemplates: 
                  "application/json": "{\"statusCode\": 200}"
              TimeoutInMillis: 29000
              Type: "MOCK"

  emptyModel:
        Type: "AWS::ApiGateway::Model"
        Properties:
            RestApiId: !Ref restAPI
            Name: "Empty"
            Description: "This is a default empty schema model"
            Schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "title" : "Empty Schema",
                  "type" : "object"
                }
            ContentType: "application/json"

  errorModel:
      Type: "AWS::ApiGateway::Model"
      Properties:
          RestApiId: !Ref restAPI
          Name: "Error"
          Description: "This is a default error schema model"
          Schema: |
              {
                "$schema" : "http://json-schema.org/draft-04/schema#",
                "title" : "Error Schema",
                "type" : "object",
                "properties" : {
                  "message" : { "type" : "string" }
                }
              }
          ContentType: "application/json"


  apiDeployment:
      Type: "AWS::ApiGateway::Deployment"
      Properties:
          RestApiId: !Ref restAPI

  devStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
          StageName: "Development"
          DeploymentId: !Ref apiDeployment
          RestApiId: !Ref restAPI
          CacheClusterEnabled: false
          CacheClusterSize: "0.5"
          TracingEnabled: false

  prodStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
          StageName: "Production"
          DeploymentId: !Ref apiDeployment
          RestApiId: !Ref restAPI
          CacheClusterEnabled: false
          CacheClusterSize: "0.5"
          TracingEnabled: false

Outputs:
  LambdaARN:
    Value: !GetAtt lambdaFunction.Arn
  websiteBucketArn:
    Value: !GetAtt websiteBucket.Arn
  comboTableArn:
    Value: !GetAtt comboTable.Arn
  templateBucketArn:
    Value: !GetAtt templateBucket.Arn
  RestApiId:
    Value: !GetAtt restAPI.RestApiId
  RestApiResourceId:
    Value: !GetAtt restAPI.RootResourceId
  RootGETMethodName:
    Value: !Ref RootGETMethod
  RootPOSTMethodName:
    Value: !Ref RootPOSTMethod
  comboANYMethodName:
    Value: !Ref comboANYMethod
  emptyModelName:
    Value: !Ref emptyModel
  errorModelName:
    Value: !Ref errorModel
  devStageName:
    Value: !Ref devStage
  prodStageName:
    Value: !Ref prodStage
  apiDeploymentId:
    Value: !GetAtt apiDeployment.DeploymentId

  WebsiteURL:
    Value: !GetAtt
      - websiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  WebsiteSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - websiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
      