name: Run Jest Tests

on:
  pull_request:
    branches:
      - main # or your default branch name
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: List directory contents
      run: ls -la src/

    - name: Run Jest tests
      run: npm test
